=== thianxin95/IP-assigment/ReportXML/Daily_OrderProcessed.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT DailyOrderRecord (Record)>
<!ELEMENT Record (OrderCount, Date, TotalAmount, OrderTypeCount)>
<!ATTLIST Record recordID ID #REQUIRED>
<!ELEMENT OrderCount (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT TotalAmount (#PCDATA)>
<!ELEMENT OrderTypeCount (DeliveryCount, PickupCount)>
<!ELEMENT DeliveryCount (#PCDATA)>
<!ELEMENT PickupCount (#PCDATA)>

=== thianxin95/IP-assigment/ReportXML/Daily_OrderProcessed.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE DailyOrderRecord SYSTEM "Daily_OrderProcessed.dtd">
<DailyOrderRecord>
    
    <Record recordID="RID1">
        <OrderCount>0</OrderCount>
        <Date>01/08/2018</Date>
        <TotalAmount>0</TotalAmount>
        <OrderTypeCount>
            <DeliveryCount>0</DeliveryCount>
            <PickupCount>0</PickupCount>
        </OrderTypeCount>
    </Record>

</DailyOrderRecord>
