=== thianxin95/IP-assigment/Employee/ReportXML/Daily_OrderProcessed.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT DailyOrderRecord (Record)>
<!ELEMENT Record (OrderPaid,OrderCanceled, Date, AmountPaid, OrderTypeCount)>
<!ATTLIST Record recordID ID #REQUIRED>
<!ELEMENT OrderPaid (#PCDATA)>
<!ELEMENT OrderCanceled (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT AmountPaid (#PCDATA)>
<!ELEMENT OrderTypeCount (DeliveryCount, PickupCount)>
<!ELEMENT DeliveryCount (#PCDATA)>
<!ELEMENT PickupCount (#PCDATA)>

=== thianxin95/IP-assigment/Employee/ReportXML/Daily_OrderProcessed.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="DailyOrderProcessedReport.xsl" type="text/xsl" ?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE DailyOrderRecord SYSTEM "Daily_OrderProcessed.dtd">
<DailyOrderRecord>
    
    
    
<Record recordID="RID1"><OrderPaid>9</OrderPaid><OrderCanceled>5</OrderCanceled><Date>04/08/2018</Date><AmountPaid>6000</AmountPaid><OrderTypeCount><DeliveryCount>7</DeliveryCount><PickupCount>7</PickupCount></OrderTypeCount></Record></DailyOrderRecord>
