=== thianxin95/IP-assigment/LeeThianXin/View/catalogItem.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT CatalogRecord (CatalogRow+)>
<!ELEMENT CatalogRow (productCode, productType, productQuantity, totalPrice, userID, userType)>
<!ELEMENT productCode (#PCDATA)>
<!ELEMENT productType (#PCDATA)>
<!ELEMENT productQuantity (#PCDATA)>
<!ELEMENT totalPrice (#PCDATA)>
<!ELEMENT userID (#PCDATA)>
<!ELEMENT userType (#PCDATA)>

=== thianxin95/IP-assigment/LeeThianXin/View/CatalogItem.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE CatalogRecord SYSTEM "catalogItem.dtd">
<CatalogRecord>
    <CatalogRow>
  <productCode>PDR1</productCode>
  <productType>Flower</productType>
  <productQuantity>24</productQuantity>
  <totalPrice>240</totalPrice>
  <userID>lee95</userID>
  <userType>Customer</userType>
</CatalogRow>
 <CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>2</productQuantity><totalPrice>60</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD4</productCode><productType>Flower</productType><productQuantity>20</productQuantity><totalPrice>800</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD2</productCode><productType>Flower</productType><productQuantity>50</productQuantity><totalPrice>1000</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD1</productCode><productType>Flower</productType><productQuantity>200</productQuantity><totalPrice>2000</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productType><productQuantity>100</productQuantity><totalPrice>3000</totalPrice><userID>lee95</userID><userType>lee95</userType></CatalogRow><CatalogRow><productCode>PRD3</productCode><productType>Flower</productTyp
