=== thianxin95/IP-assigment/LeeThianXin/View/reviewOrder.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT OrderDetail (Record+)>
<!ELEMENT Record (orderID,userID, orderDate, Pickup, DeliveryAddress, RequiredDate,TotalAmount,Status)>
<!ATTLIST Record recordID ID #REQUIRED>
<!ELEMENT orderID (#PCDATA)>
<!ELEMENT userID (#PCDATA)>
<!ELEMENT orderDate (#PCDATA)>
<!ELEMENT Pickup (#PCDATA)>
<!ELEMENT DeliveryAddress (#PCDATA)>
<!ELEMENT RequiredDate (#PCDATA)>
<!ELEMENT TotalAmount (#PCDATA)>
<!ELEMENT Status (#PCDATA)>

=== thianxin95/IP-assigment/LeeThianXin/View/reviewOrder.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE OrderDetail SYSTEM 'reviewOrder.dtd'>

<OrderDetail>
    <Record recordID= "ORD1">
        <orderID></orderID>
            
        
            <userID> </userID>
           
            
            <orderDate></orderDate>
            <Pickup></Pickup>
            <DeliveryAddress></DeliveryAddress>
            <RequiredDate></RequiredDate>
            <TotalAmount></TotalAmount>
            <Status></Status>
    </Record>                              
 
</OrderDetail>
