=== thianxin95/IP-assigment/Catalog/FlowerCatalog.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="catalogs">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="catalog" type="catalogType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="catalogID" type="xs:ID" use="required"/>
            <xs:attribute name="month" type="monthType" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="catalogType">
        <xs:sequence>
            <xs:element name="code" type="xs:string" />
            <xs:element name="type" type="xs:string"/>
            <xs:element name="description" type="xs:string" />
            <xs:element name="stock" type="xs:string" />
            <xs:element name="price" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="monthType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="January"/>
            <xs:enumeration value="February"/>
            <xs:enumeration value="March"/>
            <xs:enumeration value="April"/>
            <xs:enumeration value="May"/>
            <xs:enumeration value="June"/>
            <xs:enumeration value="July"/>
            <xs:enumeration value="August"/>
            <xs:enumeration value="September"/>
            <xs:enumeration value="October"/>
            <xs:enumeration value="November"/>
            <xs:enumeration value="December"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== thianxin95/IP-assigment/Catalog/xsl/flowercatalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
author : Chen Chun Hang
-->


<catalogs
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='FlowerCatalog.xsd'>
    <catalog>
        <code></code>
        <type></type>
        <description></description>
        <stock></stock>
        <price></price>
    </catalog>
    <catalog>
        <code></code>
        <type></type>
        <description></description>
        <stock></stock>
        <price></price>
    </catalog>
    <catalog>
        <code></code>
        <type></type>
        <description></description>
        <stock></stock>
        <price></price>
    </catalog>

</catalogs>
